#!/bin/bash

# TYPO3 git reset code to master helper
#
# optionally link up to TYPO3
#
# @author Michael Cannon <mc@aihr.us>

if [[ ! -e .git ]]
then
	echo Need to run within top-level Git clone
fi

if [[ -e typo3temp/Cache ]]
then
	sudo rm -rf typo3temp/Cache
fi

git reset --hard origin/master

if [[ -z ${1} ]]
then
	git clean -fd

	if [[ ! -e typo3_src ]]
	then
		ln -s ${SITES}${TYPO3_MASTER} typo3_src
	fi

	if [[ ! -e index.php ]]
	then
		ln -s typo3_src/index.php index.php
	fi

	if [[ ! -e t3lib ]]
	then
		ln -s typo3_src/t3lib t3lib
	fi

	if [[ ! -e typo3 ]]
	then
		ln -s typo3_src/typo3 typo3
	fi

	sudo websitepermissions michael www devo
fi