#!/bin/bash

# TYPO3 Introduction Package helper tool
#
# reset TYPO3 IP package
# link up TYPO3
#
# @author Michael Cannon <michael@typo3vagabond.com>

SITES="${HOME}/Sites/"
TYPO3_MASTER='typo3_src-master'
VHOST='t3ip'

SITES_VHOST="${SITES}${VHOST}"

if [[ ! -e ${SITES_VHOST} ]]
then
	echo "Virtual host instance ${VHOST} doesn't exist"
	exit
fi

cd ${SITES_VHOST}

if [[ -e typo3temp/Cache ]]
then
	sudo rm -rf typo3temp/Cache
fi

git reset --hard origin/master
git clean -fd

if [[ ! -e typo3_src ]]
then
	ln -s ${SITES}${TYPO3_MASTER} typo3_src
fi

if [[ ! -e index.php ]]
then
	ln -s typo3_src/index.php index.php
fi

if [[ ! -e t3lib ]]
then
	ln -s typo3_src/t3lib t3lib
fi

if [[ ! -e typo3 ]]
then
	ln -s typo3_src/typo3 typo3
fi

sudo websitepermissions michael www devo