#!/bin/bash

# Convert Dreamweaver template to HTML
#
# @author Michael Cannon, michael@typo3vagabond.com

# @param string filepath to template
# @param string html filepath, default index.htm

# has at least one arguement
if [ -z ${1} ]
then
	echo usage: `basename ${0}` template_filepath [html_filepath]
	exit
else
	TMPL=${1}
	DATE=`date +'%F_%T'`
fi

# check that TMPL exists
if [ ! -f ${TMPL} ]
then
	echo Template: ${TMPL} doesn\'t exist. Please recheck
	exit
fi

# alternate html file
if [ ! -z ${2} ]
then
	HTML=${2}
else
	HTML=index.htm
fi

# backup HTML is needed
if [ -f ${HTML} ]
then
	mv ${HTML} ${HTML}.${DATE}
fi

# cp TMPL to HTML
cp ${TMPL} ${HTML}

# remove ../ from HTML
perl -pi -e "s#\.\./##g" ${HTML}

# viola, we hope we're done
exit 0
