#!/bin/bash

# Correct CVS owner, group, and user permissions
#
# @author Michael Cannon, michael@peimic.com
# @version $Id: fixcvsperms,v 1.1.1.1 2010/04/14 09:05:44 peimic.comprock Exp $

CVS_DIR="/home/cvs/cvsroot"
CVS_OWNER="cannon"
CVS_GROUP="cvs"

# Normals
# chown it all to ${CVS_OWNER}
# chgrp it all to ${CVS_GROUP}
# 2775 directories
# 0664 files
# 0775 or a+x .sh
chown -R ${CVS_OWNER}:${CVS_GROUP} ${CVS_DIR}
find ${CVS_DIR} -type d -exec chmod 2775 {} \;
find ${CVS_DIR} -type f -exec chmod 0664 {} \;
find ${CVS_DIR} -type f \( -name "*.cgi" -o -name "*.pl" -o -name "*.sh" \) \
	-exec chmod a+x {} \;

# Specials
# chgrp cb_projects and other restricted to ${CVS_OWNER}
# chgrp special projects as needed
# 2770 directories
# 0660 files
# 0770 or a+x .sh
PROTECT_DIR="commercial-third-party"
PROTECT_DIR=""

for pDir in ${PROTECT_DIR}
do
	chgrp -R ${CVS_OWNER} ${CVS_DIR}/${pDir}
	chmod -R o-rwx ${CVS_DIR}/${pDir}
done

# correct root bin perms
chgrp -R ${CVS_OWNER} ${CVS_DIR}/root
chmod -R ug+x ${CVS_DIR}/root/bin

# correct mrtg script perms
cd ${CVS_DIR}/cb/mrtg-snmp/mrtg
chmod ug+x check-email,v  email-* system,v indexmaker.sh,v 
cd -

# allow nom access
chown -R nom:nom ${CVS_DIR}/client/mcmedia

# allow savvymiss access
chgrp -R savvymiss ${CVS_DIR}/client/savvymiss

# separate typo3 access
chgrp -R typo3 ${CVS_DIR}/typo3

# allow CVS users access to the repository files
chgrp -R cvs ${CVS_DIR}/CVSROOT

# separate piap access
chgrp -R piap ${CVS_DIR}/typo3/piap_*
