#!/bin/bash

# @author Michael Cannon <mc@aihr.us>

# have an arguement
if [ ! "$1" ]
then
	echo "Usage: `basename $0` [file]"
	exit
fi

FILE=$1

for DOMAIN in `cat ${FILE}`
do
	echo open http://${DOMAIN}
	open http://${DOMAIN}
done